In [3]:
from numpy import random
MyList=random.randint(100,size=30)
MyList.resize(10,3)
print(MyList)

[[65 71 53]
 [58 84 19]
 [12 58 65]
 [60 83 52]
 [19 94 59]
 [50 96 96]
 [31 33 59]
 [51  5  4]
 [28  9 33]
 [10 24 10]]
